name: CI

on:
  push:
    branches: master
  pull_request:
    branches: master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      actions: write
    container:
      image: freedesktopsdk/sdk:24.08-x86_64

    steps:
      - uses: actions/checkout@v4

      - name: Build and install
        env:
          FLATPAK_ID: com.example.DummyEditor
        run: |
          set -e
          meson \
            --prefix=$(pwd)/ide-wrapper-build \
            -Deditor_binary=/bin/echo \
            -Deditor_args='["--some-option"]' \
            -Deditor_title='Test dummy editor' \
            -Dprogram_name=dummy-editor \
            -Dflagfile_prefix=dummy \
            build
          ninja -C build
          ninja -C build install

      - uses: actions/upload-artifact@v4
        with:
          name: ide-wrapper-build
          path: ide-wrapper-build

      - name: Install shellcheck
        run: |
          set -e -o pipefail
          shopt -s failglob
          shellcheck_tarball="shellcheck.tar.xz"
          shellcheck_url=$(curl -sL https://api.github.com/repos/koalaman/shellcheck/releases/latest | \
            jq -r '.assets | map(select(.name | endswith("linux.x86_64.tar.xz"))) | first | .browser_download_url')
          curl -sL -o "$shellcheck_tarball" "$shellcheck_url"
          tar -xJf "$shellcheck_tarball"
          install -Dm755 shellcheck-*/shellcheck /usr/local/bin/shellcheck

      - name: Run shellcheck
        run: |
          shellcheck --severity=style ide-wrapper-build/bin/dummy-editor

